"""Runs a user's code against a question's test cases.

READ THIS BEFORE YOU START.

This runs code that a stranger typed into a text box. Do NOT use exec() or
eval() in this process. If you do, a submission can read DATABASE_URL, drop
every table, or read any file on the machine that runs the API. That is not
a hypothetical, it's about four lines of Python.

How it actually works, one subprocess per test case:

  1. a fresh temp directory holds three files -
       solution.py  the user's code, verbatim
       runner.py    RUNNER below, our harness
       input.json   the argument list for this one test
  2. spawn `python -I -S -B runner.py <function_name>` with cwd set to that
     directory and a hand-built env that simply does not contain DATABASE_URL
  3. wait SECONDS_PER_TEST, then kill the whole process group
  4. read one line of json back and compare it to the expected value

Writing the user's code as its own file (rather than pasting it into the
harness) means SyntaxError line numbers and tracebacks match what they typed
in the editor exactly - the harness never shifts the line count.

Nothing in here raises on a bad submission. A syntax error, a crash, an
infinite loop and a value json can't serialise are all just a failed test
with an `error` on it. tests/unit/test_judge.py is the spec.

WHAT A SUBMISSION CAN AND CANNOT DO
-----------------------------------
Stopped:
  - reading DATABASE_URL or any other secret  (env is a fresh dict)
  - importing psycopg, fastapi, or anything else from our venv  (-S)
  - writing files anywhere                    (RLIMIT_FSIZE 0)
  - eating memory or cpu                      (RLIMIT_AS, RLIMIT_CPU)
  - running forever                           (timeout + killpg)
  - hiding a fake result in its own stdout    (fd 1 goes to /dev/null)
  - reaching postgres over the network        (unshare --net, WHERE AVAILABLE)

Not stopped, and you should know it:
  - READING files. It can read this file, db.py, and anything else the api
    user can read. Nothing secret should live on that filesystem.
  - Networking when `unshare --net` isn't available - docker's default
    seccomp profile blocks the unshare syscall, so a container build may
    silently fall back to an open network stack. -S is what stops the easy
    version of that attack (import psycopg, connect to the url hardcoded in
    db.py, drop every table). It is a speed bump, not a boundary: stdlib
    sockets are still there.

The real fix for both is os-level isolation - run the judge as a separate
unprivileged user, in its own container, on a network that can't see the
database. Until then this is a trainee sandbox, not a hostile-internet one.
"""

import functools
import json
import os
import pathlib
import shutil
import signal
import subprocess
import sys
import tempfile

from models import TestCase, TestResult

SECONDS_PER_TEST = 5
MEMORY_LIMIT_BYTES = 256 * 1024 * 1024

# a fresh dict, NOT a filtered copy of os.environ. anything not listed here
# doesn't exist inside the subprocess, so there's no blocklist to keep up to
# date - DATABASE_URL and every future secret are absent by construction.
SAFE_ENV = {
    "PATH": "/usr/bin:/bin",
    "LC_ALL": "C.UTF-8",
    "PYTHONIOENCODING": "utf-8",
}

# runs one test case and writes a single json object to fd 3... except there
# is no fd 3, so it dups fd 1 first. see the comment in the source below.
RUNNER = '''\
# generated by judge.py - do not edit here, edit RUNNER in judge.py
import json
import os
import sys
import traceback

# fd 1 is the only channel back to the judge, and the submission is free to
# print. so: keep a private duplicate of it, then point the real fd 1 at
# /dev/null. a print(), an os.write(1, ...) and a c extension writing straight
# to the descriptor all land in the bin instead of corrupting our json.
REPLY_FD = os.dup(1)
os.dup2(os.open(os.devnull, os.O_WRONLY), 1)
sys.stdout = open(os.devnull, "w")

# soft AND hard set to the same number, so the submission can't raise them
# back up. the wall-clock timeout in judge.py is the real backstop; these stop
# a submission eating the whole machine before it gets there.
try:
    import resource

    resource.setrlimit(resource.RLIMIT_CPU, (@@CPU_SECONDS@@, @@CPU_SECONDS@@))
    resource.setrlimit(resource.RLIMIT_AS, (@@MEMORY_BYTES@@, @@MEMORY_BYTES@@))
    resource.setrlimit(resource.RLIMIT_FSIZE, (0, 0))  # no writing files at all
except (ImportError, ValueError):
    pass  # not linux, or something already set a lower limit. keep going.

HERE = os.path.dirname(os.path.abspath(__file__))
# -I keeps the script's directory off sys.path, which is what we want by
# default. put it back deliberately, and only it, so `import solution` finds
# the submission and nothing else in this directory can shadow the stdlib.
sys.path.insert(0, HERE)


def reply(payload):
    os.write(REPLY_FD, json.dumps(payload).encode())
    # _exit, not sys.exit: SystemExit can be swallowed by a submission's
    # try/except, and atexit handlers it registered must not run after this.
    os._exit(0)


def fail(message):
    reply({"ok": False, "error": message})


def describe(exc, drop_frames=0):
    """The traceback, minus our own frames at the top of it."""
    tb = exc.__traceback__
    for _ in range(drop_frames):
        if tb is None:
            break
        tb = tb.tb_next
    return "".join(traceback.format_exception(type(exc), exc, tb)).strip()


function_name = sys.argv[1]
with open(os.path.join(HERE, "input.json")) as handle:
    args = json.load(handle)

try:
    import solution
except SyntaxError as exc:
    # format_exception_only keeps the offending line and the caret, which is
    # the whole value of a syntax error. no traceback frames to show.
    fail("".join(traceback.format_exception_only(type(exc), exc)).strip())
except BaseException as exc:
    fail("your code crashed before it could be run\\n\\n" + describe(exc, drop_frames=1))

function = getattr(solution, function_name, None)
if function is None:
    fail("your code doesn't define a function called " + function_name + "()")
if not callable(function):
    fail(function_name + " is defined, but it isn't a function")

try:
    value = function(*args)
except BaseException as exc:
    fail(describe(exc, drop_frames=1))

try:
    body = json.dumps({"ok": True, "result": value})
except (TypeError, ValueError):
    fail(
        "returned a " + type(value).__name__ + ", which can't be sent back as "
        "json. return a list, dict, string, number, bool or None."
    )

os.write(REPLY_FD, body.encode())
os._exit(0)
'''

RUNNER_SOURCE = RUNNER.replace(
    # one second of headroom: the wall clock in the parent should be what
    # trips first, because "timed out" is a clearer message than SIGXCPU.
    "@@CPU_SECONDS@@",
    str(SECONDS_PER_TEST + 1),
).replace("@@MEMORY_BYTES@@", str(MEMORY_LIMIT_BYTES))


@functools.cache
def _network_isolation() -> tuple[str, ...]:
    """`unshare --net`, if this kernel hands it out without root. Cached.

    A submission can't read DATABASE_URL, but db.py has the dev url written
    into it as a default and the whole repo is public - so "no env" alone
    never stopped `connect to postgres and drop everything`, it just made the
    attacker type the url. A network namespace with no interfaces does stop
    it: postgres becomes 'Network is unreachable'.

    --map-root-user is what makes this work unprivileged; the resulting root
    is root inside the namespace only. Costs about 2ms per test.

    Falls back to an empty prefix wherever the syscall is refused (docker's
    default seccomp profile, macos, older kernels). See the docstring at the
    top of this module for what that costs you.
    """
    unshare = shutil.which("unshare")
    if unshare is None:
        return ()

    prefix = (unshare, "--net", "--map-root-user")
    try:
        probe = subprocess.run(
            [*prefix, sys.executable, "-I", "-S", "-c", ""],
            capture_output=True,
            timeout=10,
        )
    except (OSError, subprocess.SubprocessError):
        return ()
    return prefix if probe.returncode == 0 else ()


def _kill_process_group(process: subprocess.Popen) -> None:
    # subprocess.run's timeout kills only the direct child, then blocks in
    # communicate() waiting on a pipe a surviving grandchild still holds open.
    # start_new_session gave the submission its own process group, so one
    # killpg takes the lot and that hang can't happen.
    try:
        os.killpg(os.getpgid(process.pid), signal.SIGKILL)
    except (ProcessLookupError, PermissionError, AttributeError):
        process.kill()  # already dead, or a platform without process groups


def _judge(workdir: str, function_name: str) -> tuple[dict | None, str | None]:
    """Runs the prepared directory. Returns (reply, error) - exactly one is set."""
    process = subprocess.Popen(
        # -I isolated (no PYTHON* vars, no user site), -S no site-packages at
        # all, -B no .pyc files. -S is the one that matters: without it the
        # submission can `import psycopg` straight out of our venv.
        # solutions get the standard library and nothing else.
        [*_network_isolation(), sys.executable, "-I", "-S", "-B", "runner.py", function_name],
        cwd=workdir,
        env=SAFE_ENV,
        stdin=subprocess.DEVNULL,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        errors="replace",  # a submission can print bytes that aren't utf-8
        start_new_session=True,
    )

    try:
        stdout, stderr = process.communicate(timeout=SECONDS_PER_TEST)
    except subprocess.TimeoutExpired:
        _kill_process_group(process)
        try:
            stdout, stderr = process.communicate(timeout=SECONDS_PER_TEST)
        except subprocess.TimeoutExpired:  # pragma: no cover - killpg failed
            stdout, stderr = "", ""
        return None, (
            f"timed out after {SECONDS_PER_TEST} seconds. "
            "is there a loop that never finishes?"
        )

    def scrub(text: str) -> str:
        # tracebacks name the temp directory. the user should see
        # 'File "solution.py", line 2', not a path on our server.
        return text.replace(workdir + os.sep, "").replace(workdir, "")

    if not stdout.strip():
        if process.returncode is not None and process.returncode < 0:
            return None, (
                f"the code was killed by signal {-process.returncode} - it "
                "probably used too much memory or cpu"
            )
        message = "the code exited without returning a result"
        detail = scrub(stderr).strip()
        if detail:
            message += "\n\n" + detail[-800:]
        return None, message

    try:
        reply = json.loads(stdout)
    except json.JSONDecodeError:  # pragma: no cover - would be a bug in RUNNER
        return None, "the judge couldn't read the result of your code"

    if not reply.get("ok"):
        return None, scrub(reply.get("error") or "the code failed for an unknown reason")
    return reply, None


def run_one_test(code: str, function_name: str, test: TestCase) -> TestResult:
    # run code in a subprocess, call function_name(*test.input), compare to
    # test.expected. a crash or timeout is a failed test, not an exception
    with tempfile.TemporaryDirectory(prefix="judge-") as workdir:
        directory = pathlib.Path(workdir)
        (directory / "solution.py").write_text(code, encoding="utf-8")
        (directory / "runner.py").write_text(RUNNER_SOURCE, encoding="utf-8")
        (directory / "input.json").write_text(json.dumps(test.input), encoding="utf-8")

        reply, error = _judge(workdir, function_name)

    if error is not None:
        return TestResult(
            passed=False, input=test.input, expected=test.expected, error=error
        )

    assert reply is not None  # _judge sets exactly one of the two
    got = reply["result"]
    # `got` has been through json on the way here, so a returned tuple is
    # already a list by now and compares equal to an expected list.
    return TestResult(
        passed=got == test.expected,
        input=test.input,
        expected=test.expected,
        got=got,
    )


def run_submission(
    code: str, function_name: str, tests: list[TestCase]
) -> list[TestResult]:
    # run every test, return a result for each. don't stop at the first fail,
    # the user wants to see all of them
    return [run_one_test(code, function_name, test) for test in tests]
